name: Generate Docblocks (v1) [Automated]

on:
  push:
    branches:
      - v1.x
  workflow_dispatch:

jobs:
  generate:
    name: Generated TSDoc PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "v1.x"

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Install docs-util Dependencies
        run: yarn
        working-directory: docs-util

      - name: Build packages
        run: yarn build
        working-directory: docs-util
      
      - name: Check Commit
        id: check-commit
        run: 'yarn check:release-commit ${{ github.sha }}'
        working-directory: docs-util/packages/scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_OWNER: ${{ github.repository_owner }}
          GIT_REPO: medusa

      - name: Run docblock generator
        if: steps.check-commit.outputs.is_release_commit == 'true'
        run: "yarn start run:release"
        working-directory: docs-util/packages/docblock-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_OWNER: ${{ github.repository_owner }}
          GIT_REPO: medusa

      - name: Generate Changeset
        if: steps.check-commit.outputs.is_release_commit == 'true'
        run: "yarn generate:changeset"
        working-directory: docs-util/packages/scripts

      - name: Create Pull Request
        if: steps.check-commit.outputs.is_release_commit == 'true'
        uses: peter-evans/create-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "chore(docs): Generated TSDocs"
          body: "This PR holds all generated TSDocs for the upcoming release."
          branch: "chore/generate-tsdocs"
          add-paths: packages/**
  generate-oas:
    name: Generated OAS PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "v1.x"

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Install docs-util Dependencies
        run: yarn
        working-directory: docs-util

      - name: Build packages
        run: yarn build
        working-directory: docs-util
      
      - name: Check Commit
        id: check-commit
        run: 'yarn check:release-commit ${{ github.sha }}'
        working-directory: docs-util/packages/scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_OWNER: ${{ github.repository_owner }}
          GIT_REPO: medusa

      - name: Run docblock generator
        if: steps.check-commit.outputs.is_release_commit == 'true'
        run: "yarn start run ../../../packages/medusa/src/api-v2 --type oas && yarn start clean:oas"
        working-directory: docs-util/packages/docblock-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_OWNER: ${{ github.repository_owner }}
          GIT_REPO: medusa

      - name: Create Pull Request
        if: steps.check-commit.outputs.is_release_commit == 'true'
        uses: peter-evans/create-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          base: "v1.x"
          title: "chore(docs): Generated OAS"
          body: "This PR holds all generated OAS for the upcoming release."
          branch: "chore/generate-oas"
          add-paths: docs-util/oas-output/**